//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoaBinhTools.FramingInformation {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Save : global::System.Configuration.ApplicationSettingsBase {
        
        private static Save defaultInstance = ((Save)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Save())));
        
        public static Save Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string ConcreteCover {
            get {
                return ((string)(this["ConcreteCover"]));
            }
            set {
                this["ConcreteCover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string StirrupDia {
            get {
                return ((string)(this["StirrupDia"]));
            }
            set {
                this["StirrupDia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string StirrupSup {
            get {
                return ((string)(this["StirrupSup"]));
            }
            set {
                this["StirrupSup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string StirrupSpan {
            get {
                return ((string)(this["StirrupSpan"]));
            }
            set {
                this["StirrupSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Stirrup_HookStart {
            get {
                return ((string)(this["Stirrup_HookStart"]));
            }
            set {
                this["Stirrup_HookStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Stirrup_HookEnd {
            get {
                return ((string)(this["Stirrup_HookEnd"]));
            }
            set {
                this["Stirrup_HookEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Link_HookStart {
            get {
                return ((string)(this["Link_HookStart"]));
            }
            set {
                this["Link_HookStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Anchorage_Top {
            get {
                return ((string)(this["Anchorage_Top"]));
            }
            set {
                this["Anchorage_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Anchorage_Bot {
            get {
                return ((string)(this["Anchorage_Bot"]));
            }
            set {
                this["Anchorage_Bot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Lap_Tension {
            get {
                return ((string)(this["Lap_Tension"]));
            }
            set {
                this["Lap_Tension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Lap_Comp {
            get {
                return ((string)(this["Lap_Comp"]));
            }
            set {
                this["Lap_Comp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string Link_HookEnd {
            get {
                return ((string)(this["Link_HookEnd"]));
            }
            set {
                this["Link_HookEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string TL_top {
            get {
                return ((string)(this["TL_top"]));
            }
            set {
                this["TL_top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string TL_bot {
            get {
                return ((string)(this["TL_bot"]));
            }
            set {
                this["TL_bot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10M")]
        public string AddStirup_Dia {
            get {
                return ((string)(this["AddStirup_Dia"]));
            }
            set {
                this["AddStirup_Dia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public string AddStirrup_Spc {
            get {
                return ((string)(this["AddStirrup_Spc"]));
            }
            set {
                this["AddStirrup_Spc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Is_SameAsMain {
            get {
                return ((int)(this["Is_SameAsMain"]));
            }
            set {
                this["Is_SameAsMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Is_CStirrup {
            get {
                return ((bool)(this["Is_CStirrup"]));
            }
            set {
                this["Is_CStirrup"] = value;
            }
        }
    }
}
